name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub (optional)
        if: false
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t crm-message-server:latest .

      - name: Save Docker image
        run: |
          docker save crm-message-client:latest | gzip > image.tar.gz

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          SSH_PORT: "22"
        run: |
          # Transfer Docker image to server
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -P ${SSH_PORT} image.tar.gz $SSH_USER@$SSH_HOST:/tmp/

          # SSH into server and deploy
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -p ${SSH_PORT} $SSH_USER@$SSH_HOST << 'ENDSSH'
            # Load Docker image
            docker load < /tmp/image.tar.gz
            rm /tmp/image.tar.gz
            
            # Stop and remove existing container
            docker stop crm-message-server || true
            docker rm crm-message-server || true
            
            # Run new container
            docker run -d \
              --name crm-message-server \
              --restart unless-stopped \
              -p 8000:8000 \
              crm-message-server:latest
            
            # Clean up old images
            docker image prune -f
          ENDSSH

      - name: Cleanup
        if: always()
        run: |
          rm -f image.tar.gz